### PR TITLE
Added WrappingGrid extension for wrapping header texts. Added demo fo…

### PR DESCRIPTION
**Pull request by TatuLund**
…r header wrapping. Updated version to 0.2.3. Upgraded the demo project to use Vaadin-7.5.10.

[Review on Reviewable](https://reviewable.io/reviews/tsuoanttila/gridextensionpack/10)

### CODE REVIEW

**Comment by TatuLund** [comment]
I forgot to update Readme.md yesterday. It should be here now.

**Comment by tsuoanttila** [comment]
Reviewed 7 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[GridExtensionPack-demo/src/main/java/org/vaadin/teemusa/gridextensions/demo/HeaderWrapExtensionLayout.java, line 2 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p3ViTvrGIPyAOyDDo:-K5p3ViTvrGIPyAOyDDp:-1002345009) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack-demo/src/main/java/org/vaadin/teemusa/gridextensions/demo/HeaderWrapExtensionLayout.java#L2)):*
Inconsistent use of tabs and spaces.  I'll have to reformat the files...

---

*[GridExtensionPack/pom.xml, line 13 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p3rUFJkblNVQDkq-6:-K5p3rUGQUG8aOe01Zvz:-1538204025) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/pom.xml#L13)):*
I'd prefer to compile this still against the 7.5.0 just to make sure it's usable in all 7.5 versions

---

*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingClientRPC.java, line 7 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4-3UVWY0Pw1_qG4e:-K5p4-3UVWY0Pw1_qG4f:1008364515) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingClientRPC.java#L7)):*
missing javadoc on methods. Even though it's "internal API" some basic documentation to make it more maintainable would be nice. Also, why not .setWrapping(boolean enabled) ?

---

*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingGridConnector.java, line 184 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4N3-hfLxzVyHscRt:-K5p4N3-hfLxzVyHscRu:-1582165894) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingGridConnector.java#L184)):*
Add onUnregister and do a proper clean up. I'll have to review this file for real sometime soon...

---

*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/wrappinggrid/WrappingGrid.java, line 9 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4XWWpMMSc0VdrsTy:-K5p4XWWpMMSc0VdrsTz:1941258606) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/wrappinggrid/WrappingGrid.java#L9)):*
basic javadoc would be nice

---

*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/wrappinggrid/WrappingGrid.java, line 19 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4bJbIW6IKWkZOldJ:-K5p4bJbIW6IKWkZOldK:2084704184) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/wrappinggrid/WrappingGrid.java#L19)):*
see comment in RPC interface.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingClientRPC.java, line 7 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4-3UVWY0Pw1_qG4e:-K6n9ppIXiQxebygHiea:-1820841363) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingClientRPC.java#L7)):*
I guess it's "Good enough"

---

*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingGridConnector.java, line 184 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4N3-hfLxzVyHscRt:-K6n9yfMq0XqbpKRjlJt:-859417769) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingGridConnector.java#L184)):*
This still needs addressing. Test with setWrapping(true) and then call .remove() on the extension.

---

*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/wrappinggrid/WrappingGrid.java, line 9 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4XWWpMMSc0VdrsTy:-K6nACcJbmJemGiBpZ34:-1078235154) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/wrappinggrid/WrappingGrid.java#L9)):*
This still needs a basic "What does this extension do" JavaDoc

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10)*

**Comment by tsuoanttila** [comment]
*[GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingGridConnector.java, line 184 \[r1\]](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10#-K5p4N3-hfLxzVyHscRt:-K6nF3jQKoaRbmzpOsdz:1840441146) ([raw file](https://github.com/tsuoanttila/gridextensionpack/blob/1c9c35b32f8fcb3f2c7835b853cef50c5fb10884/GridExtensionPack/src/main/java/org/vaadin/teemusa/gridextensions/client/wrappinggrid/WrappingGridConnector.java#L184)):*
Well, if it works, then it shall be fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tsuoanttila/gridextensionpack/10)*

**Pull request merged**
